spring.application.name=aviation
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/aviation_new_db
spring.datasource.username=root
spring.datasource.password=Thunderstorm11
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG